# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: ${RESTART:-no}
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=vocdoni
      - MONGO_INITDB_DATABASE=oauth
    volumes:
      - mongodb:/data/mongodb

  blind-csp:
    build:
      context: ../
    image: ghcr.io/vocdoni/blind-csp:${CSP_TAG:-master}
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - mongo
    sysctls:
      net.core.somaxconn: 8128
    volumes:
      - blind-csp:/app/data
      - "./handlerFiles:/handlerFiles"
    restart: ${RESTART:-no}

volumes:
  blind-csp: {}
  mongodb: {}
